project:
  type: website
  output-dir: docs
website:
  title: "Alex Singleton"
  navbar:
    pinned: true
    left:
      - href: index.qmd
        text: Home
      - href: cv.pdf
        text: CV
      - papers.qmd
      - books.qmd
      - blog.qmd

format:
  html:
    theme: superhero
    css: styles.css
    toc: true

editor: visual

