on
  workflow_dispatch
  push
    branches main

name Quarto Publish

jobs
  build-deploy
    runs-on ubuntu-latest
    permissions
      contents write
    steps
      - name Check out repository
        uses actionscheckout@v2

      - name Set up Quarto
        uses quarto-devquarto-actionssetup@v2

      - name Render and Publish
        uses quarto-devquarto-actionspublish@v2
        with
          target gh-pages
        env
          GITHUB_TOKEN ${{ secrets.GITHUB_TOKEN }}